name: sample-nestjs-app
services:
- name: web
  source_dir: /
  github:
    repo: AiStartup101/sample-nodejs
    branch: main
  run_command: npm run start:prod
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  health_check:
    http_path: /api/v1/health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: NPM_CONFIG_PRODUCTION
    value: "true"
  autoscaling:
    min_instance_count: 1
    max_instance_count: 5
    cpu_utilization_percentage: 70
  alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: HIGH_CPU_UTILIZATION
    threshold: 80
  - rule: HIGH_MEMORY_UTILIZATION
    threshold: 80
